<?php if($this->identity): ?>
<p>ok</p>

<?php else: ?>
    <div class="container-fluid">
        <div class="row">
            <section>
                <div class="col-xs-6 col-xs-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
                    <?php
                        echo $this->form;
                    ?>

                </div>
            </section>
        </div>
    </div>

<?php endif ?>