<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/vendor/bootstrap/css/bootstrap.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/validationEngine.jquery.css'); ?>

    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js');?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.validationEngine.js');?>

</head>
    <body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->baseUrl; ?>/public/index/index">Головна</a>
            </div>

            <ul class="nav navbar-nav">
                <li class="active"><a href="<?= $this->baseUrl; ?>/public/table/index">Таблиця <span class="sr-only">(current)</span></a></li>
            </ul>
            <?php
            $auth = Zend_Auth::getInstance();
            $acl = Zend_Registry::get('acl');
            $role = $auth->getIdentity()->role;
            if( $role != 'admin') { ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?= $this->baseUrl; ?>/public/auth/login">Увійти <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            <?php
            }else { ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?= $this->baseUrl; ?>/public/auth/logout">Вийти <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            <?php } ?>
        </div>
    </nav>
        <div class="jumbotron">
            <h1>Тестове завдання</h1>
            <h3>Піцун Олег</h3>
        </div>
    <div id="content">

        <?php echo $this->layout()->content; ?>
    </div>

    </body>
</html>
